/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndanh_mytranslator_jni_NativeMarkerDetector */

#ifndef _Included_com_ndanh_mytranslator_jni_NativeMarkerDetector
#define _Included_com_ndanh_mytranslator_jni_NativeMarkerDetector
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_ndanh_mytranslator_jni_NativeMarkerDetector_nativeCreateObject
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);


JNIEXPORT jobjectArray JNICALL
Java_com_ndanh_mytranslator_jni_NativeMarkerDetector_nativeFindMarkers
        (JNIEnv *, jobject, jlong, jlong, jlong, jfloat);


JNIEXPORT void JNICALL Java_com_ndanh_mytranslator_jni_NativeMarkerDetector_nativeDestroyObject
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
